# Docker aliases
alias composer='docker run --rm -it -v `pwd`:/app -w /app wodby/drupal-php:8.1-dev-macos-4.42.12 composer '
alias drush='docker run --rm -it -p 8080:8080 -v `pwd`:/app -w /app wodby/drupal-php:8.1-dev-macos-4.42.12 drush '
alias node='docker run --rm -it -v `pwd`:/app -w /app wodby/node:18-dev-1.19.0 '
alias npm='docker run --rm -it -p 8080:8080 -v `pwd`:/app -w /app wodby/node:18-dev-1.19.0 npm '
alias npx='docker run --rm -it -v `pwd`:/app -w /app wodby/node:18-dev-1.19.0 npx '
alias yarn='docker run --rm -it -p 8080:8080 -v `pwd`:/app -w /app wodby/node:18-dev-1.19.0 yarn '
alias php='docker run --rm -it -p 8080:8080 -v `pwd`:/app -w /app wodby/drupal-php:8.1-dev-macos-4.42.12 php '
alias aws='docker run --rm -it -v ~/.aws:/root/.aws -v `pwd`:/aws amazon/aws-cli '
alias jupyter='docker run --rm -it -p 8888:8888 -e GRANT_SUDO=yes --user root -v `pwd`:/home/jovyan jupyter/tensorflow-notebook:latest '
